# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout 
      # run tests!
      - run: npm test
  deploy_to_recette:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
  deploy_to_prod:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
workflows:
  version: 2
  dev_test_to_recette:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      #require need 2 tab
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
      - deploy_to_recette:
          requires:
            - test
          filters:
             branches:
               only:
                - develop 
  recette_test_to_prod:
    jobs:
      - build:
          filters:
            branches:
              only: recette
      - test:
          filters:
            branches:
              only: recette
      - deploy_to_prod:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: recette
      
 
